### PR TITLE
Add async and lodash to package.json

### PR DESCRIPTION
**Pull request by svanherk**
Fixes running tests in local browsers

### CODE REVIEW

**Comment by svanherk** [comment]
Haven't merged this yet as it will start causing these errors in GitHub: https://github.com/BrightspaceUI/time-picker.

What do people think is better?  Those security alerts, or the fail message in local testing?

FYI @omsmith

**Comment by mdgbayly** [comment]
> Haven't merged this yet as it will start causing these errors in GitHub: https://github.com/BrightspaceUI/time-picker.

Where do these errors show up? I'm not seeing anything.

I think I'm OK either way. It's only a dev dependency which is going to be installed regardless, but not sure if that makes it any less/more of a threat.

It is kind of ugly to include it when we don't specifically depend on it. So if people can confirm that it only throws the error on test initialization and doesn't actually affect the running of the tests, then I'm OK to drop it.  Maybe we should be using yarn so we could at least use the resolutions feature.

**Comment by omsmith** [comment]
@mdgbayly you need be an admin of the repo for it to appear. Here's an example:
alert

**Comment by omsmith** [comment]
My concern is that this is going to add a lot of noise to the security alerts. We'll get used to seeing a banner on our repos, and learn to ignore it. We'll get e-mail notifications when this is added to each repo, and learn to ignore them. They'll be included in the weekly security alert digest e-mail, and learn to ignore it.

**Comment by dlockhart** [comment]
@svanherk probably close-worthy at this point?

**Comment by svanherk** [comment]
Yeah, I don't want to be adding those security alerts to all of our repos.

**Pull request closed without merging**
